services:
  habits_mysql:
    image: mysql
    restart: always
    container_name: habits_mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3306
    volumes:
      - 'habits-mysql:/var/lib/mysql'
    networks:
      - habits-network

  habits_fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
    restart: unless-stopped
    ports:
      - 9000
    volumes:
      - habits-production:/var/www/habits
    env_file:
      - .env
    networks:
      - proxy-network
      - habits-network

  habits_cli:
    volumes:
      - habits-production:/var/www/habits
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    tty: true
    stdin_open: true
    env_file:
      - .env
    networks:
      - habits-network

networks:
  habits-network:
    driver: bridge
  proxy-network:
    external: true

volumes:
  habits-production:
    external: true
  habits-mysql:
    driver: local
