services:
    habit_mysql:
        image: mysql
        restart: always
        container_name: habbit_mysql
        env_file: .env
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '3306:3306'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    habit_php:
        build: ./docker
        container_name: habbit_php
        ports:
            - 9000:9000
        volumes:
            - .:/var/www:cached

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
